Kyori Components
MrMicky-FR/FastBoard pull request #24
Opened 2022-11-17 11:59 UTC by rexlManu

My pr removes mostly of the legacy handling of prior version 1.17 and introduces kyori components instead of strings.

I don't think it makes sense, merge this with the main branch. My goal is to provide a "newer" version with kyori components in a separate branch or even repo? Maybe we could also convert this project in a multi project.

Anyway I created this pr, so other folks can just copy the classes with kyori as alternative instead of strings.

Have a good day!

2022-11-17 12:08 UTC, MrMicky-FR commented
Hi, thanks for your pull request, please just keep the current formatting (4 spaces) because currently the diff is impossible to review

2022-11-17 12:41 UTC, rexlManu commented
Oh yea, sorry for that. I'm used to just apply the google java styling conventions. Fixed it.

2023-02-18 15:42 UTC, Doc94 commented
Hi, any update about this feature?

2023-02-18 16:42 UTC, MrMicky-FR commented
> Hi, any update about this feature?

Unfortunately not yet: Adventure support is still planned but I have no ETA, and this PR is almost a complete rewrite of FastBoard (drops support for lots of old versions and remove Bukkit/Spigot support) so I cannot directly merge it without introducing breaking changes for almost all FastBoard users 😐

2023-02-18 23:46 UTC, Doc94 commented
> > Hi, any update about this feature?
> 
> Unfortunately not yet: Adventure support is still planned but I have no ETA, and this PR is almost a complete rewrite of FastBoard (drops support for lots of old versions and remove Bukkit/Spigot support) so I cannot directly merge it without introducing breaking changes for almost all FastBoard users 😐

okay, and understand maybe if this PR support the "legacy" method can be great.
unless exists a form to transform the component to the legacy text for use with this lib?

2023-02-19 06:22 UTC, MrMicky-FR commented
> > > Hi, any update about this feature?
> > 
> > 
> > Unfortunately not yet: Adventure support is still planned but I have no ETA, and this PR is almost a complete rewrite of FastBoard (drops support for lots of old versions and remove Bukkit/Spigot support) so I cannot directly merge it without introducing breaking changes for almost all FastBoard users 😐
> 
> okay, and understand maybe if this PR support the "legacy" method can be great. unless exists a form to transform the component to the legacy text for use with this lib?

You can use the [Legacy Serializer](https://docs.adventure.kyori.net/serializer/legacy.html) to convert components from/to strings

2023-02-19 10:08 UTC, rexlManu commented
Hey, it depends on the use case but I think it doesn't make sense to support legacy versions because adventure is non existence prior >1.16. So thats why I dropped it and yea it doesnt' make sense to merge it, I just open this pr to provide a alternative version.

2023-02-19 14:47 UTC, Doc94 commented
> > > > Hi, any update about this feature?
> > > 
> > > 
> > > Unfortunately not yet: Adventure support is still planned but I have no ETA, and this PR is almost a complete rewrite of FastBoard (drops support for lots of old versions and remove Bukkit/Spigot support) so I cannot directly merge it without introducing breaking changes for almost all FastBoard users 😐
> > 
> > 
> > okay, and understand maybe if this PR support the "legacy" method can be great. unless exists a form to transform the component to the legacy text for use with this lib?
> 
> You can use the [Legacy Serializer](https://docs.adventure.kyori.net/serializer/legacy.html) to convert components from/to strings

Nice, this works perfect for convert.



> Hey, it depends on the use case but I think it doesn't make sense to support legacy versions because adventure is non existence prior >1.16. So thats why I dropped it and yea it doesnt' make sense to merge it, I just open this pr to provide a alternative version.

yeah not sure what can be better, if add support to the two things and make maybe component convert to legacy text for allow old server can use adventure in old systems (?, or make the breaking and drop backcompatibility (?

2023-02-19 16:17 UTC, rexlManu commented
The problem is that old versions don't have adventure. So it need to be 2 versions of the lib anyway.

2023-04-07 15:54 UTC, portlek requested changes

2023-04-07 15:58 UTC, rexlManu commented on src/main/java/fr/mrmicky/fastboard/FastBoard.java
> +        setField(packet, int.class, mode.ordinal(), 1); // Update mode
Thanks for the report. Fixed it.

2023-04-07 16:07 UTC, rexlManu commented
I was thinking again about that. We could support both when we use object class and check on building if it's components and if the server is running a new version otherwise convert them to legacy text. This change would introduce a lot of reflection and a possible dependency with kyori if components are used.

I could create that and PR it, but just want to know if that's even needed.

2023-04-07 16:12 UTC, portlek commented
you can make it work with 1 abstract class and 2 implementation both string and component for the packet writing parts i guess.

2023-04-07 18:02 UTC, rexlManu commented
> you can make it work with 1 abstract class and 2 implementation both string and component for the packet writing parts i guess.

I would do it like that if it's fine when api break changes are okay.

2023-04-07 19:54 UTC, MrMicky-FR commented
> > you can make it work with 1 abstract class and 2 implementation both string and component for the packet writing parts i guess.
> 
> I would do it like that if it's fine when api break changes are okay.

Hi, I already tried splitting FastBoard into an interface with two implementations (String and Component) but I couldn’t get good results without lot of duplicated code, which would highly impact maintainability, but I will give it a new try this week!

About a PR for this split, yes it would be great, but the key considerations would be to not have too much duplicate code and keep the current features, like legacy versions compatibility, almost single-class import (including without Maven/Gradle, even if importing through it is recommended), Bukkit (non-Paper) support, … 
Breaking changes are fine, as it would be released as a v2.0.0.

2023-04-08 11:51 UTC, MrMicky-FR commented
> you can make it work with 1 abstract class and 2 implementation both string and component for the packet writing parts i guess.

I managed to get a pretty good result, I've pushed it on the [dev branch](https://github.com/MrMicky-FR/FastBoard/tree/dev), not tested yet but at least it compiles. Feel free to add feedback in the commit, will open a draft PR when tested :)

2023-04-08 11:58 UTC, rexlManu commented
Looks good, I would suggust to add a check if the server is running on paper otherwise convert it  back to strings with the legacy serializer from kyori.

That would fix the problem when a author wants to use kyori but the plugin needs to run on like 1.12, the components will be serialized back to old color codes, if we want to keep the support from 1.8 until 1.19.4. Otherwise its fine to drop support for that for kyori components.

2023-05-01 07:21 UTC, rexlManu commented
Due the implementation and the currently draft pr from Micky, I will close this pr.

2023-05-01 07:21 UTC, closed without merging