Add support for 1.20.4 fixed formatting
MrMicky-FR/FastBoard pull request #46
Opened 2023-12-30 20:15 UTC by blubbarbs

This PR adds support for the 1.20.4 fixed formatting for the scoreboard scores. I tested this on Paper 1.19.4 so backwards compatibility should be working. The only underlying change to the protocol is the `FixedFormat`  NMS objects that get sent from `sendModernScorePacket()` instead of `BlankFormat` objects if the score's text has been set.

2023-12-30 20:42 UTC, MrMicky-FR commented
Thank you for your pull request but I’m not sure to understand exactly how it would look in game and the advantages of this, if you could provide an ingame screenshot with the explanations about the advantages for this, it would be perfect! Thanks

2024-01-10 12:39 UTC, xism4 approved these changes

2024-02-14 02:07 UTC, vicen621 commented
Any news on this pr? I found this very usefull and seems ready to be merged

2024-02-14 15:18 UTC, MrMicky-FR commented
Hi, sorry for the long delay, I've pushed some changes with the goal of simplify cross-version (between pre and post 1.20.3) handling: the behavior of the scores is always the same, but of course the custom scores are only displayed on 1.20.3+

Reviews & comments are welcome :)

2024-02-15 20:20 UTC, syldium requested changes
Great addition!

2024-02-15 20:20 UTC, syldium commented on src/main/java/fr/mrmicky/fastboard/FastBoardBase.java
> +     * @throws IllegalArgumentException if the size of the texts does not match the current size of the board
```suggestion
     * @throws IllegalArgumentException if the line number is not in range
```

2024-02-15 20:20 UTC, syldium commented on src/main/java/fr/mrmicky/fastboard/FastBoardBase.java
> +        updateScore(line, emptyLine());
```suggestion
        updateScore(line, null);
```
Technically, an empty score is not the same as a score with an empty text.

2024-02-15 20:20 UTC, syldium commented on src/main/java/fr/mrmicky/fastboard/FastBoardBase.java
> +     * @throws IllegalArgumentException if the size of the texts does not match the current size of the board
```suggestion
     * @throws IllegalArgumentException if the line number is not in range
```

2024-02-16 03:05 UTC, vicen621 approved these changes
Looks good to me, nice additions!

2024-02-16 03:06 UTC, vicen621 commented on src/main/java/fr/mrmicky/fastboard/FastBoardBase.java
> +     * @throws IllegalArgumentException if the size of the texts does not match the current size of the board
I think the comment is better understood in this way

2024-02-16 07:54 UTC, MrMicky-FR commented
Good catches @syldium , thanks!

2024-02-24 13:21 UTC, merged