Add mojang mapped class
MrMicky-FR/FastBoard pull request #57
Opened 2024-07-03 12:08 UTC by Dominilk01

Yea i know its not the best code, but well it worked to me with mojang mapping

2024-07-04 20:05 UTC, syldium requested changes

2024-07-04 20:05 UTC, syldium commented on src/main/java/fr/mrmicky/fastboard/FastBoardBase.java
> +                    .orElse(FastReflection.nmsClass("server.level", "ServerPlayer"));
The Mojang mapped class name will always be looked for, even if `EntityPlayer` is found. And on Spigot servers, `ServerPlayer` doesn't exist, so this code fails.

Unfortunately, making the call lazy with [`Optional#orElseGet`](https://docs.oracle.com/en/java/javase/21/docs/api/java.base/java/util/Optional.html#orElseGet(java.util.function.Supplier)) would make the code quite verbose and not ideal:
```java
Class<?> entityPlayerClass = FastReflection.nmsOptionalClass("server.level", "EntityPlayer")
      .orElseGet(() -> {
          try {
              return FastReflection.nmsClass("server.level", "ServerPlayer");
          } catch (ClassNotFoundException ex) {
              throw new RuntimeException(ex);
          }
      });
```

I *think* `FastReflection#nmsClass` could be updated to allow multiple class names to be searched and could (ab)use the fact that both mappings use the same package names:
```java
Class<?> entityPlayerClass = FastReflection.nmsClass("server.level", "EntityPlayer", "ServerPlayer");
```

2024-07-04 23:33 UTC, Dominilk01 commented
I thinker that if value not found then it will call the orElse. Il check it tomorrow and update it

2024-07-05 21:15 UTC, Dominilk01 commented
Don't mind me [syldium](https://github.com/syldium) i stole your idea of a method that accept both ;)

2024-07-06 14:55 UTC, MrMicky-FR commented
I pushed changes in `FastReflection` to avoid throwing/catching a dozen of `ClassNotFoundException`, tested and seems to work fine on all versions, but feel free to review before I merge this 😃

2024-07-06 15:29 UTC, syldium approved these changes
Tested on Spigot 1.8.8, Paper+Bukkit plugin 1.21, Paper+non remapped Bukkit plugin 1.21 and Paper dev server 1.21.

2024-07-07 15:34 UTC, merged